apiVersion: v1
kind: Service
metadata:
  name: devops
  namespace: namespace-workflow-1691417183526
spec:
  type: LoadBalancer
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000